<?php
/**
 * Implements hook_menu().
 */
function rsi_ws_menu() {
	$items = array();
	
	$items['admin/config/services/rsi'] = array(
			'title' => 'RSI Webservices',
			'description' => 'RSI webservices settings',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('rsi_ws_settings_form'),
			'access arguments' => array('administer RSI'),
			'file' => 'rsi_ws.admin.inc',
			'type' => MENU_NORMAL_ITEM,
	);
	$items['ticket-office-shows'] = array(
			'title' => 'Shows list',
			'page callback' => 'rsi_shows_list',
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);
	$items['ticket-office-show/%'] = array(
			'title' => 'Show details',
			'page callback' => 'rsi_show',
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);
	$items['ticket-office-event/%'] = array(
			'title' => 'Event details',
			'page callback' => 'rsi_event',
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}

/**
 * Callback functions.
 */

function rsi_shows_list() {
	$shows = rsi_get_shows();
	
	$items = array();
	$popup_width = variable_get('rsi_popup_width', '');
	$popup_height = variable_get('rsi_popup_height', '');
// 	foreach ($shows as $show) {
// 		$url = $show['URL'] . '&width=' . $popup_width . '&height=' . $popup_height . '&iframe=true';
// 		$item = l($show['SUMMARY'], $url, array('attributes' => array('class' => array('colorbox-load'))));
// 		$items[] = $item;
// 	}
	$boxoffice_domain = rsi_get_domain();
	foreach($shows as $show) {
		$id_spectacle = $show['@attributes']['IDENT'];
		$url = $boxoffice_domain . 'spectacle?id_spectacle=' . $id_spectacle . '&width=' . $popup_width . '&height=' . $popup_height . '&iframe=true';
		$item = l($show['@attributes']['NOM'], $url, array('attributes' => array('class' => array('colorbox-load'))));
		$items[] = $item;
	}
	
	$variables = array(
		'items' => $items,
		'type' => 'ul',
	);
	return theme('item_list', $variables);
}

function rsi_show() {
	$show = rsi_get_show(arg(1));
	//dpm($show);
	
	$output = '';
	$output .= theme('html_tag', array(
		'element' => array(
			'#tag' => 'h2',
			'#value' => $show[0]['SUMMARY'],
		),
	));
	$output .= theme('html_tag', array(
			'element' => array(
					'#tag' => 'span',
					'#value' => $show[0]['X_RSI_LOCATION'],
			),
	));
	$items = array();
	foreach ($show as $event) {
		$event_date = format_date(strtotime($event['DTSTART']), 'custom', 'l d F Y - H\hi');
		$item = l($event_date, 'ticket-office-event/' . $event['X_RSI_REPRESENTATION_ID']);
		$items[] = $item;
	}
	
	//return 'DETAILS SPECTACLE';
	$variables = array(
			'items' => $items,
			'title' => t('Select an event'),
			'type' => 'ul',
	);
	$output .= theme('item_list', $variables);
	
	return $output;
}

function rsi_event() {
	$event = rsi_get_event(arg(1));
	dpm($event);
	return 'DETAILS REPRESENTATION';
}

/**
 * Helper functions.
 */

function rsi_get_shows() {
	$boxoffice_domain = rsi_get_domain();
	if ($boxoffice_domain == '/') {
		return t(
				'RSI webservices are not set up yet. Go to <a href="@link">admin page</a> and set them up.',
				array('@link' => url('admin/config/services/rsi')
				)
		);
	}
	$ws_list_name = variable_get('rsi_ws_show_list_name', '');
	$credentials = rsi_ws_credentials();
	$url = $boxoffice_domain . $ws_list_name . '?' . $credentials;
	return rsi_get_ws_data('list', $url);
}

function rsi_get_show($show_id) {
	$boxoffice_domain = rsi_get_domain();
	$ws_show_name = variable_get('rsi_ws_show_name', '');
	$url = $boxoffice_domain . $ws_show_name . '?id_spectacle=' . $show_id;
	
	return rsi_get_ws_data('show', $url);
}

function rsi_get_event($event_id) {
	$boxoffice_domain = rsi_get_domain();
	$ws_event_name = variable_get('rsi_ws_event_name', '');
	$url = $boxoffice_domain . $ws_event_name . '?id_event=' . $event_id;

	return rsi_get_ws_data('event', $url);
}

function rsi_get_programmation() {
	$boxoffice_domain = rsi_get_domain();
	$ws_prog = variable_get('rsi_ws_prog', '');
	$ws_login  = variable_get('rsi_login', '');
	$ws_pass = variable_get('rsi_pass', '');
	$ws_client = variable_get('rsi_client', '');
	$url = $boxoffice_domain . $ws_prog . '?x_rsi_ws_login=' . $ws_login . '&x_rsi_ws_mdp=' . $ws_pass . '&x_rsi_client=' . $ws_client; 
	
	return rsi_get_ws_data('prog', $url);
}

function rsi_get_ws_data($type, $url) {
// 	// first access to catch session cookie
// 	$http_resp1 = drupal_http_request($url);
// 	$cookie_data = explode(';', $http_resp1->headers['set-cookie']);
// 	$options = array(
// 			'headers' => array(
// 					'Cookie' => $cookie_data[0] . ';sessionstate=1',
// 			),
// 	);
// 	// second access, using the session cookie, to get data.
// 	$http_resp2 = drupal_http_request($url, $options);
// 	$json = $http_resp2->data;
// 	$data = drupal_json_decode($json);

	$response = drupal_http_request($url);
	
	switch ($type) {
		case 'prog':
			$data = new SimpleXMLElement($response->data);
			$data = drupal_json_decode(drupal_json_encode($data));
			return $data;
			break;
		case 'list':
// 			$data = drupal_json_decode($response->data);
// 			return $data['vcalendar']['VEVENT'];
			$data = new SimpleXMLElement($response->data);
			$data = drupal_json_decode(drupal_json_encode($data));
			return $data['SPECTACLES']['SPECTACLE'];
			break;
		case 'show' :
			$data = drupal_json_decode($response->data);
			return $data['vcalendar']['VEVENT'];
			break;
		default:
			return $data;
	}
}

function rsi_ws_credentials () {
	$ws_login  = variable_get('rsi_login', '');
	$ws_pass = variable_get('rsi_pass', '');
	$ws_client = variable_get('rsi_client', '');
	
	return 'x_rsi_ws_login=' . $ws_login . '&x_rsi_ws_mdp=' . $ws_pass . '&x_rsi_client=' . $ws_client;
}

function rsi_get_domain() {
	$domain = variable_get('rsi_ws_url', '');
	if ($domain{strlen($domain) -1} != '/') {
		return $domain . '/';
	}
	return $domain;
}



